// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pin.DartsTournament.Infrastructure.Data;

#nullable disable

namespace Pin.DartsTournament.Infrastructure.Migrations
{
    [DbContext(typeof(DartsDbContext))]
    [Migration("20220106175525_AddPlayerGames")]
    partial class AddPlayerGames
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Pin.DartsTournament.Core.Entities.Dart", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"), 1L, 1);

                    b.Property<long?>("LegId")
                        .HasColumnType("bigint");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LegId");

                    b.ToTable("Darts", (string)null);
                });

            modelBuilder.Entity("Pin.DartsTournament.Core.Entities.Game", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"), 1L, 1);

                    b.Property<long?>("RefereeId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TournamentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RefereeId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("Pin.DartsTournament.Core.Entities.Leg", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"), 1L, 1);

                    b.Property<long?>("GameId")
                        .HasColumnType("bigint");

                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Legs", (string)null);
                });

            modelBuilder.Entity("Pin.DartsTournament.Core.Entities.Player", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"), 1L, 1);

                    b.Property<int>("Losses")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("TournamentId")
                        .HasColumnType("bigint");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("Players", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Losses = 0,
                            Name = "Jane Doe",
                            Wins = 0
                        },
                        new
                        {
                            Id = 2L,
                            Losses = 0,
                            Name = "John Doe",
                            Wins = 0
                        },
                        new
                        {
                            Id = 3L,
                            Losses = 0,
                            Name = "Harry Potter",
                            Wins = 0
                        },
                        new
                        {
                            Id = 4L,
                            Losses = 0,
                            Name = "Mr. Anderson",
                            Wins = 0
                        },
                        new
                        {
                            Id = 5L,
                            Losses = 0,
                            Name = "Pablo Picasso",
                            Wins = 0
                        },
                        new
                        {
                            Id = 6L,
                            Losses = 0,
                            Name = "Johan Vermeer",
                            Wins = 0
                        });
                });

            modelBuilder.Entity("Pin.DartsTournament.Core.Entities.PlayerGame", b =>
                {
                    b.Property<long>("PlayerId")
                        .HasColumnType("bigint");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint");

                    b.HasKey("PlayerId", "GameId");

                    b.HasIndex("GameId");

                    b.ToTable("PlayerGame", (string)null);
                });

            modelBuilder.Entity("Pin.DartsTournament.Core.Entities.Referee", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("TournamentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("Referees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 30L,
                            Name = "Lector Deboosere"
                        },
                        new
                        {
                            Id = 31L,
                            Name = "Lector Derdeyn"
                        });
                });

            modelBuilder.Entity("Pin.DartsTournament.Core.Entities.Tournament", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Tournaments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 100L,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Conf-IT-uurtjes Toernooi"
                        });
                });

            modelBuilder.Entity("Pin.DartsTournament.Core.Entities.Dart", b =>
                {
                    b.HasOne("Pin.DartsTournament.Core.Entities.Leg", null)
                        .WithMany("Throws")
                        .HasForeignKey("LegId");
                });

            modelBuilder.Entity("Pin.DartsTournament.Core.Entities.Game", b =>
                {
                    b.HasOne("Pin.DartsTournament.Core.Entities.Referee", null)
                        .WithMany("Games")
                        .HasForeignKey("RefereeId");

                    b.HasOne("Pin.DartsTournament.Core.Entities.Tournament", null)
                        .WithMany("Games")
                        .HasForeignKey("TournamentId");
                });

            modelBuilder.Entity("Pin.DartsTournament.Core.Entities.Leg", b =>
                {
                    b.HasOne("Pin.DartsTournament.Core.Entities.Game", null)
                        .WithMany("Legs")
                        .HasForeignKey("GameId");

                    b.HasOne("Pin.DartsTournament.Core.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Pin.DartsTournament.Core.Entities.Player", b =>
                {
                    b.HasOne("Pin.DartsTournament.Core.Entities.Tournament", null)
                        .WithMany("Players")
                        .HasForeignKey("TournamentId");
                });

            modelBuilder.Entity("Pin.DartsTournament.Core.Entities.PlayerGame", b =>
                {
                    b.HasOne("Pin.DartsTournament.Core.Entities.Game", "Game")
                        .WithMany("PlayerGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pin.DartsTournament.Core.Entities.Player", "Player")
                        .WithMany("PlayerGames")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Pin.DartsTournament.Core.Entities.Referee", b =>
                {
                    b.HasOne("Pin.DartsTournament.Core.Entities.Tournament", null)
                        .WithMany("Referees")
                        .HasForeignKey("TournamentId");
                });

            modelBuilder.Entity("Pin.DartsTournament.Core.Entities.Game", b =>
                {
                    b.Navigation("Legs");

                    b.Navigation("PlayerGames");
                });

            modelBuilder.Entity("Pin.DartsTournament.Core.Entities.Leg", b =>
                {
                    b.Navigation("Throws");
                });

            modelBuilder.Entity("Pin.DartsTournament.Core.Entities.Player", b =>
                {
                    b.Navigation("PlayerGames");
                });

            modelBuilder.Entity("Pin.DartsTournament.Core.Entities.Referee", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("Pin.DartsTournament.Core.Entities.Tournament", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("Players");

                    b.Navigation("Referees");
                });
#pragma warning restore 612, 618
        }
    }
}
